<a href="https://colab.research.google.com/github/topkek777/tf-homework/blob/master/lr0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Работа №0

# To Do:
1) Create a vector, scalar, matrix and tensor with values of your choosing using
tf.constant().

2) Find the shape, rank and size of the tensors you created in 1.

3) Create two tensors containing random values between 0 and 1 with shape [5, 300].

4) Multiply the two tensors you created in 3 using matrix multiplication.

5) Multiply the two tensors you created in 3 using dot product.

6) Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7) Find the min and max values of the tensor you created in 6.

8) Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9) Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10) One-hot encode the tensor you created in 9.

In [1]:
import tensorflow as tf

1) Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [3]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(42)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([42, 42])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 42], dtype=int32)>

In [5]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
# Create a tensor
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

2) Find the shape, rank and size of the tensors you created in 1.

Shape: The length (number of elements) of each of the dimensions of a tensor.

Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

Axis or Dimension: A particular dimension of a tensor.

Size: The total number of items in the tensor.

In [16]:
print('Shapes:', scalar.shape, vector.shape, matrix.shape, tensor.shape)
print('Ranks:', scalar.ndim, vector.ndim, matrix.ndim, tensor.ndim)
print('Sizes:', tf.size(scalar), tf.size(vector), tf.size(matrix), tf.size(tensor))

Shapes: () (2,) (2, 2) (2, 2, 2)
Ranks: 0 1 2 3
Sizes: tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(4, shape=(), dtype=int32) tf.Tensor(8, shape=(), dtype=int32)


3) Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [17]:
tensor1 = tf.random.uniform(shape=[5, 300])
tensor2 = tf.random.uniform(shape=[5, 300])

4) Multiply the two tensors you created in 3 using matrix multiplication.

In [20]:
result = tf.multiply(tensor1, tensor2)
result

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.33430195, 0.00598932, 0.20101441, ..., 0.03991862, 0.32227737,
        0.43753165],
       [0.32950863, 0.08231224, 0.09359987, ..., 0.1770603 , 0.5018234 ,
        0.31827858],
       [0.56578106, 0.4458176 , 0.7470795 , ..., 0.27803767, 0.0473389 ,
        0.43611044],
       [0.88283485, 0.5720689 , 0.629519  , ..., 0.0438647 , 0.39843524,
        0.00623489],
       [0.83110607, 0.6718983 , 0.47449124, ..., 0.36884633, 0.05151011,
        0.62479776]], dtype=float32)>

5) Multiply the two tensors you created in 3 using dot product.

In [23]:
dot_result = tf.matmul(tf.transpose(tensor1), tensor2)
dot_result

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[2.9435327 , 2.5184865 , 2.4776802 , ..., 1.6358689 , 2.4877474 ,
        2.497054  ],
       [2.2264597 , 1.7780864 , 2.0321155 , ..., 1.1612139 , 1.2108742 ,
        1.479272  ],
       [2.5054176 , 2.0282588 , 2.145704  , ..., 1.4873158 , 1.9705812 ,
        2.0787296 ],
       ...,
       [2.1801107 , 2.1264164 , 1.8597579 , ..., 0.9077276 , 1.7707038 ,
        1.7317197 ],
       [1.4229778 , 1.2461083 , 1.2647132 , ..., 0.62122005, 1.321385  ,
        0.97276264],
       [2.055008  , 1.477285  , 1.8463737 , ..., 1.523009  , 1.628463  ,
        1.8229532 ]], dtype=float32)>

6) Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [24]:
tensor3 = tf.random.uniform(shape=[224, 224, 3])

7) Find the min and max values of the tensor you created in 6.

In [26]:
min_val = tf.reduce_min(tensor3)
max_val = tf.reduce_max(tensor3)
print("min:", min_val, "max:", max_val)

min: tf.Tensor(1.0728836e-06, shape=(), dtype=float32) max: tf.Tensor(0.99999547, shape=(), dtype=float32)


8) Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [28]:
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])

squeezed_tensor = tf.squeeze(tensor4)
print(squeezed_tensor.shape)

(224, 224, 3)


9) Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [30]:
tensor5 = tf.constant([5, 7, 2, 8, 1, 9, 3, 6, 4, 0])

max_index = tf.argmax(tensor)
print("Index of maximum value:", max_index.numpy())

Index of maximum value: 5


10) One-hot encode the tensor you created in 9.

In [31]:
one_hot_tensor = tf.one_hot(tensor, depth=10)

print("Original Tensor:", tensor.numpy())
print("One-hot Encoded Tensor:\n", one_hot_tensor.numpy())

Original Tensor: [5 7 2 8 1 9 3 6 4 0]
One-hot Encoded Tensor:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
